env: safetyGraphics
label: AE Tornado Plot Module
type: module
package: tornadoplot
export: false
order: 1
domain:
  - aes
  - dm
workflow:
  init: init_tornado
  ui: tornado_ui
  server: tornado_server
links:
  tornadoplot: https://github.com/SafetyGraphics/volcanoPlot
